from rich.console import Console
console = Console()

AzulyBlanco = "bold white on blue"
RojoyBlanco = "bold white on red"
AmarilloyBlanco = "bold white on yellow"

def cucaracha_img():
      print('            -=+-=-.             :===+::                  ')
      print('                  .:-+ +**=:        .=***--+ -                  ')
      print('                   .::=+****=      =******=::                   ')
      print('              .          -***+    +****=:                       ')
      print('           =-===+=         =**+  -***=.       .-:==.:           ')
      print('         ---+-+++:          +**:.***-         :++==-=::.        ')
      print('          :+=++++=+-      :-=+*+=*=+=-      .--=++=+==:         ')
      print('          :=====+-.      .:-+ +*+* +-::     .:-+======          ')
      print('           =+*+=.         :---****+::.         :=+++=:          ')
      print('            #%+              .****:              -%%-           ')
      print('     .:    :=*-:          .--==++=---           .-+*:           ')
      print(' . *+*==   - + =         .=--=.+::=--=.         = * -  .++-=:   ')
      print(' ++=+#+====.=-==:        =---=*==*=----        .+-=-=::.++===+: ')
      print('===*+++*==  .+---        =---=#+=#+----        ----=.-=+++++=-=-')
      print('  -+=+==+.   -=-=    .-=:=+=--=++=---*=+=:     +--=   -=====+.  ')
      print('   -++##=     =-+    -.*..++++#**#++++ +-::   .=-=.    =++==-   ')
      print('    .:#%*.    :+=-   :++=+====++++=====--*.   =-=.     .%%=:    ')
      print('      :==:::  :++++=:.+===++========++==== :-+++*.   ::=++      ')
      print('      .--::-    :=+=+++*==++++====++++=++=+===+-.    -.+ -      ')
      print('        ===-       :=++.=:.*+++++++++.* -++=-:      :+-=-.      ')
      print('         =-=          *=--=++++++++++-=:-:         .=--=        ')
      print('         .=-:        +%*++++========+++++         .=-=-         ')
      print('          :==-:::. :-##+===============++=.    ..:=-=:          ')
      print('           :-=++++=.+ =====----------=+:.=.++++==+==            ')
      print('                .:----===-------------=- =:-::::::.             ')
      print('                  .%%==-----::::::::----==+.                    ')
      print('                  -%%==----::::::::::-----=:                    ')
      print('      .:-:::::....=#*=----:::::..:::::----==.       ..          ')
      print('      - * :+=++++= * =-----::::::::::-----.=.+====+:+.-         ')
      print('      .:=-+-:::::--=-+=-----::::::::----==.-:=====+.= -.        ')
      print('        =--+      +%%*==----------------==+.     .===-          ')
      print('        ----=     :%%%====------------===+-      =--+           ')
      print('        .+--=-     #%%*+=======--========+      =----           ')
      print('         =---+.    =%%%*+++===========+++.     :=--=.           ')
      print('         -=---+     #%%#:+.=+++++++-+:++.     .=---=            ')
      print('          +==-=:    -%%#.= =******+ + -       =---=.            ')
      print('          .+ =::.    *%%%#%%#******#=:.     ..--.=-             ')
      print('           .==++     .%%%%%+=+:*%%%%-       .:::--              ')
      print('            *%@*      :%%%%::* -%%%=         +@%#               ')
      print('            +%@+       -%%%%-:+%%%=          =@%+               ')
      print('       ::-+*%%%*        :+*-  .-=.           *@%%#*=:-.         ')
      print('      *%#%#****+                             =*+++*##%#         ')

def principal():
      console.print('#####################################################', style=AzulyBlanco)
      console.print('#                    Games AnMaRu                   #', style=AzulyBlanco)
      console.print('#####################################################', style=AzulyBlanco)
      console.print('#                    La Cucaracha                   #', style=RojoyBlanco)
      console.print('#                                                   #')
      console.print('#                  [1] ► 🪳 Players 2                #')
      console.print('#                  [2] ► 🪳 Players 3                #')
      console.print('#                  [3] ► 🪳 Players 4                #')
      console.print('#                  [4] ► 🪳 Players 5                #')
      console.print('#                  [5] ► 🪳 Players 6                #')
      console.print('#                  [6] ► 🪳 Salir                    #')
      console.print('#                                                   #')
      console.print('#####################################################',style=AzulyBlanco)
      console.print('#    Seleccione una de las opciones para iniciar    #', style=AzulyBlanco)
      console.print('#####################################################', style=AzulyBlanco)

def lance_player(name_jugador):
      console.print('#####################################################', style=AzulyBlanco)
      console.print('#              🪳🪳🪳   La Cucaracha  🪳🪳🪳              #', style=AzulyBlanco)
      console.print('#####################################################', style=AzulyBlanco)
      console.print(f'|                     {name_jugador}                     |', style=RojoyBlanco)
      console.print('-----------------------------------------------------', style=AzulyBlanco)

def win_game(name_jugador, puntos):
      console.print('#####################################################', style=AmarilloyBlanco)
      console.print('#              🪳🪳🪳   La Cucaracha  🪳🪳🪳              #')
      console.print('#####################################################', style=AmarilloyBlanco)
      console.print(f'|          El {name_jugador} Ha ganado el juego           |', style=AzulyBlanco)
      console.print(f'|            Total Dinero Ganada son {puntos}             |', style=AzulyBlanco)
      console.print('-----------------------------------------------------', style=AzulyBlanco)
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆           ')
      console.print('                 🏆    🏆    🏆    🏆    🏆               ')
      console.print('                    🏆    🏆    🏆    🏆            ')
      console.print('                       🏆    🏆    🏆            ')
      console.print('                          🏆    🏆            ')
      console.print('                          🏆    🏆            ')
      console.print('                          🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('              🏆    🏆    🏆    🏆    🏆    🏆            ')
      console.print('-----------------------------------------------------', style=AzulyBlanco)


